create sequence hibernate_sequence start 1 increment 1;
create table association_value_entry (id int8 not null, association_key varchar(255) not null, association_value varchar(255), saga_id varchar(255) not null, saga_type varchar(255), primary key (id));
create table dead_letter_entry (dead_letter_id varchar(255) not null, cause_message varchar(255), cause_type varchar(255), diagnostics oid, enqueued_at timestamp not null, index int8 not null, last_touched timestamp, aggregate_identifier varchar(255), event_identifier varchar(255) not null, message_type varchar(255) not null, meta_data oid, payload oid not null, payload_revision varchar(255), payload_type varchar(255) not null, sequence_number int8, time_stamp varchar(255) not null, token oid, token_type varchar(255), type varchar(255), processing_group varchar(255) not null, processing_started timestamp, sequence_identifier varchar(255) not null, primary key (dead_letter_id));
create table saga_entry (saga_id varchar(255) not null, revision varchar(255), saga_type varchar(255), serialized_saga oid, primary key (saga_id));
create table todo_log_entry (id int8 not null, date timestamp not null, message varchar(255) not null, todo_id varchar(255) not null, primary key (id));
create table token_entry (processor_name varchar(255) not null, segment int4 not null, owner varchar(255), timestamp varchar(255) not null, token oid, token_type varchar(255), primary key (processor_name, segment));
create index IDXk45eqnxkgd8hpdn6xixn8sgft on association_value_entry (saga_type, association_key, association_value);
create index IDXgv5k1v2mh6frxuy5c0hgbau94 on association_value_entry (saga_id, saga_type);
create index IDXe67wcx5fiq9hl4y4qkhlcj9cg on dead_letter_entry (processing_group);
create index IDXrwucpgs6sn93ldgoeh2q9k6bn on dead_letter_entry (processing_group, sequence_identifier);
alter table if exists dead_letter_entry add constraint UK5o90gyvtpsxm46giirskcl486 unique (processing_group, sequence_identifier, index);
